table = [
  {
    keySource: "Ctrl\n+\nShift\n+\nEnter",
    desc: "笔记本: 在上方插入代码单元格",
  },
  {
    keySource: "Shift\n+\nAlt\n+\nDownArrow",
    desc: "笔记本: 向下复制单元格",
  },
  {
    keySource: "Shift\n+\nAlt\n+\nUpArrow",
    desc: "笔记本: 向上复制单元格",
  },
  { keySource: "Alt\n+\nDownArrow", desc: "笔记本: 下移单元格" },
  { keySource: "Ctrl\n+\nAlt\n+\nEnter", desc: "笔记本: 停止编辑单元格" },
  { keySource: "Escape", desc: "笔记本: 停止编辑单元格" },
  { keySource: "Shift\n+\nAlt\n+\nF", desc: "笔记本: 设置笔记本的格式" },
  { keySource: "Alt\n+\nUpArrow", desc: "笔记本: 上移单元格" },
  { keySource: "Delete", desc: "笔记本: 删除单元格" },
  { keySource: "Alt\n+\nDelete", desc: "笔记本: 清除单元格输出" },
  { keySource: "Ctrl\n+\nEnd", desc: "笔记本: 聚焦最后一个单元格" },
  {
    keySource: "Ctrl\n+\nDownArrow",
    desc: "笔记本: 聚焦下一个单元格编辑器",
  },
  { keySource: "DownArrow", desc: "笔记本: 聚焦下一个单元格编辑器" },
  { keySource: "UpArrow", desc: "笔记本: 聚焦上一个单元格编辑器" },
  { keySource: "Ctrl\n+\nDownArrow", desc: "笔记本: 聚焦活动单元格输出" },
  { keySource: "Ctrl\n+\nHome", desc: "笔记本: 聚焦第一个单元格" },
  { keySource: "Ctrl\n+\nUpArrow", desc: "笔记本: 解除活动单元格输出聚焦" },
  { keySource: "Y", desc: "笔记本: 将单元格更改为代码" },
  { keySource: "M", desc: "笔记本: 将单元格更改为 Markdown" },
  { keySource: "Alt\n+\nWindows\n+\nJ", desc: "笔记本: 加入下一个单元格" },
  {
    keySource: "Shift\n+\nAlt\n+\nWindows\n+\nJ",
    desc: "笔记本: 加入上一个单元格",
  },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nShift\n+\n\\",
    desc: "笔记本: 拆分单元格",
  },
  { keySource: "Enter", desc: "笔记本: 编辑单元格" },
  { keySource: "Escape", desc: "帮助: 隐藏界面概述" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nR", desc: "帮助: 键盘快捷方式参考" },
  { keySource: "Ctrl\n+\nShift\n+\nV", desc: "笔记本: 在上方粘贴单元格" },
  { keySource: "Ctrl\n+\nEnter", desc: "笔记本: 在下方插入代码单元格" },
  { keySource: "RightArrow", desc: "笔记本: 展开单元格" },
  { keySource: "Ctrl\n+\nShift\n+\n]", desc: "笔记本: 展开单元格" },
  { keySource: "Ctrl\n+\nK\nT", desc: "笔记本: 展开单元格输出" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nC", desc: "笔记本: 展开单元格输入" },
  { keySource: "LeftArrow", desc: "笔记本: 折叠单元格" },
  { keySource: "Ctrl\n+\nShift\n+\n[", desc: "笔记本: 折叠单元格" },
  { keySource: "Ctrl\n+\nK\nT", desc: "笔记本: 折叠单元格输出" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nC", desc: "笔记本: 折叠单元格输入" },
  {
    keySource: "Alt\n+\nEnter",
    desc: "笔记本: 执行笔记本单元格并在下方插入",
  },
  {
    keySource: "Shift\n+\nEnter",
    desc: "笔记本: 执行笔记本单元格并在下方选择",
  },
  { keySource: "Ctrl\n+\nAlt\n+\nEnter", desc: "笔记本: 执行单元格" },
  { keySource: "Ctrl\n+\nL", desc: "笔记本: 中心活动单元格" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nX", desc: "裁剪尾随空格" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nL", desc: "测试: 调试上次运行" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nE", desc: "测试: 调试失败的测试" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nA", desc: "测试: 调试所有测试" },
  { keySource: "Ctrl\n+\n;\nM", desc: "测试: 快速查看输出" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nI", desc: "测试: 切换内联测试输出" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nO", desc: "测试: 显示输出" },
  { keySource: "Ctrl\n+\n;\nA", desc: "测试: 运行所有测试" },
  {
    keySource: "Ctrl\n+\n;\nCtrl\n+\nF",
    desc: "测试: 在当前文件中调试测试",
  },
  { keySource: "Ctrl\n+\n;\nF", desc: "测试: 在当前文件中运行测试" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nC", desc: "测试: 在光标处调试测试" },
  { keySource: "Ctrl\n+\n;\nC", desc: "测试: 在光标处运行测试" },
  { keySource: "Ctrl\n+\nH", desc: "测试: 在速览中切换测试历史记录" },
  { keySource: "Ctrl\n+\n;\nL", desc: "测试: 重新运行上次运行" },
  { keySource: "Ctrl\n+\n;\nE", desc: "测试: 重新运行失败的测试" },
  { keySource: "Shift\n+\nAlt\n+\nF8", desc: "测试: 转到“上一个测试失败”" },
  { keySource: "Alt\n+\nF8", desc: "测试: 转到“下一个测试失败”" },
  { keySource: "Alt\n+\nZ", desc: "查看: 切换自动换行" },
  { keySource: "Ctrl\n+\nShift\n+\nF12", desc: "查看实现" },
  { keySource: "Ctrl\n+\nF", desc: "查找" },
  { keySource: "Shift\n+\nF3", desc: "查找上一个" },
  { keySource: "Shift\n+\nEnter", desc: "查找上一个" },
  { keySource: "Ctrl\n+\nShift\n+\nF3", desc: "查找上一个选择" },
  { keySource: "F3", desc: "查找下一个" },
  { keySource: "Enter", desc: "查找下一个" },
  { keySource: "Ctrl\n+\nF3", desc: "查找下一个选择" },
  { keySource: "Ctrl\n+\nZ", desc: "撤消" },
  { keySource: "Ctrl\n+\nShift\n+\nSpace", desc: "触发参数提示" },
  { keySource: "Ctrl\n+\nI", desc: "触发建议" },
  { keySource: "Ctrl\n+\nSpace", desc: "触发建议" },
  {
    keySource: "Ctrl\n+\nAlt\n+\nWindows\n+\nN",
    desc: "创建: 新建文件...",
  },
  { keySource: "Ctrl\n+\nK\nF12", desc: "打开侧边的定义" },
  { keySource: "Ctrl\n+\nShift\n+\nC", desc: "打开新的外部终端" },
  { keySource: "F9", desc: "调试: 切换断点" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nI", desc: "调试: 显示悬停" },
  { keySource: "Ctrl\n+\nInsert", desc: "复制" },
  { keySource: "Ctrl\n+\nC", desc: "复制" },
  { keySource: "Shift\n+\nAlt\n+\nF", desc: "格式化文档" },
  { keySource: "Shift\n+\nAlt\n+\nF", desc: "格式化文档" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nF", desc: "格式化选定内容" },
  { keySource: "Ctrl\n+\nF2", desc: "更改所有匹配项" },
  { keySource: "Ctrl\n+\nK\nM", desc: "更改语言模式" },
  { keySource: "Ctrl\n+\nK\nF", desc: "工作区: 关闭工作区" },
  { keySource: "Ctrl\n+\nShift\n+\nW", desc: "关闭窗口" },
  { keySource: "Alt\n+\nF4", desc: "关闭窗口" },
  { keySource: "Escape", desc: "关闭异常小组件" },
  { keySource: "Ctrl\n+\nU", desc: "光标撤消" },
  { keySource: "Alt\n+\nLeftArrow", desc: "后退" },
  { keySource: "Ctrl\n+\nShift\n+\nZ", desc: "恢复" },
  { keySource: "Ctrl\n+\nY", desc: "恢复" },
  { keySource: "Shift\n+\nDelete", desc: "剪切" },
  { keySource: "Ctrl\n+\nX", desc: "剪切" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nD",
    desc: "将上次选择移动到下一个查找匹配项",
  },
  { keySource: "Ctrl\n+\nD", desc: "将下一个查找匹配项添加到选择" },
  { keySource: "Enter", desc: "接受 REPL 的输入" },
  { keySource: "Ctrl\n+\nShift\n+\n.", desc: "聚焦到“导航路径”视图" },
  { keySource: "Ctrl\n+\nShift\n+\nI", desc: "开发人员: 切换开发人员工具" },
  { keySource: "Ctrl\n+\nR", desc: "开发人员: 重新加载窗口" },
  { keySource: "Escape", desc: "开始: 返回" },
  { keySource: "Ctrl\n+\n.", desc: "快速修复..." },
  { keySource: "Ctrl\n+\nShift\n+\nF2", desc: "启动链接编辑" },
  { keySource: "Alt\n+\nRightArrow", desc: "前进" },
  { keySource: "Ctrl\n+\nM", desc: "切换 Tab 键移动焦点" },
  { keySource: "Shift\n+\nAlt\n+\n0", desc: "切换垂直/水平编辑器布局" },
  { keySource: "Shift\n+\nAlt\n+\nA", desc: "切换块注释" },
  { keySource: "Ctrl\n+\n/", desc: "切换行注释" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nL", desc: "切换折叠" },
  { keySource: "Escape", desc: "取消选择定位点" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nJ", desc: "全部展开" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n0", desc: "全部折叠" },
  { keySource: "Ctrl\n+\nShift\n+\nB", desc: "任务: 运行生成任务" },
  { keySource: "Ctrl\n+\nShift\n+\nK", desc: "删除行" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nU", desc: "删除行注释" },
  { keySource: "Shift\n+\nAlt\n+\nF", desc: "设置单元格格式" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nB", desc: "设置选择定位点" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nP",
    desc: "视图: 按外观显示所有编辑器",
  },
  { keySource: "Ctrl\n+\nK\nEnter", desc: "视图: 保留编辑器" },
  { keySource: "Ctrl\n+\n\\", desc: "视图: 拆分编辑器" },
  { keySource: "Ctrl\n+\nPageUp", desc: "视图: 打开上一个编辑器" },
  { keySource: "Ctrl\n+\nPageDown", desc: "视图: 打开下一个编辑器" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nPageDown",
    desc: "视图: 打开组中的下一个编辑器",
  },
  { keySource: "Ctrl\n+\n9", desc: "视图: 打开组中上一个编辑器" },
  { keySource: "Alt\n+\n0", desc: "视图: 打开组中上一个编辑器" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nPageUp",
    desc: "视图: 打开组中上一个编辑器",
  },
  { keySource: "Ctrl\n+\nNumPad_Add", desc: "视图: 放大" },
  { keySource: "Ctrl\n+\nShift\n+\n=", desc: "视图: 放大" },
  { keySource: "Ctrl\n+\n=", desc: "视图: 放大" },
  { keySource: "Ctrl\n+\nK\nShift\n+\nEnter", desc: "视图: 固定编辑器" },
  { keySource: "Ctrl\n+\nW", desc: "视图: 关闭编辑器" },
  { keySource: "Ctrl\n+\nF4", desc: "视图: 关闭编辑器" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nW", desc: "视图: 关闭所有编辑器" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nShift\n+\nW",
    desc: "视图: 关闭所有编辑器组",
  },
  { keySource: "Ctrl\n+\nK\nW", desc: "视图: 关闭组中的所有编辑器" },
  { keySource: "Ctrl\n+\nK\nU", desc: "视图: 关闭组中已保存的编辑器" },
  { keySource: "Shift\n+\nAlt\n+\n1", desc: "视图: 将编辑器移动到第一组" },
  {
    keySource: "Ctrl\n+\nAlt\n+\nLeftArrow",
    desc: "视图: 将编辑器移动到上一组",
  },
  {
    keySource: "Ctrl\n+\nAlt\n+\nRightArrow",
    desc: "视图: 将编辑器移动到下一组",
  },
  {
    keySource: "Shift\n+\nAlt\n+\n9",
    desc: "视图: 将编辑器移动到最后一组",
  },
  { keySource: "Ctrl\n+\n0", desc: "视图: 聚焦到侧边栏" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nRightArrow",
    desc: "视图: 聚焦到右侧编辑器组",
  },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nLeftArrow",
    desc: "视图: 聚焦到左侧编辑器组",
  },
  { keySource: "Ctrl\n+\n1", desc: "视图: 聚焦于第一个编辑器组" },
  {
    keySource: "Ctrl\n+\nTab",
    desc: "视图: 快速打开组中上一个最近使用过的编辑器",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nTab",
    desc: "视图: 快速打开组中最近使用频率最低的编辑器",
  },
  { keySource: "Ctrl\n+\nShift\n+\nY", desc: "视图: 切换 调试控制台" },
  { keySource: "Ctrl\n+\nShift\n+\nU", desc: "视图: 切换 输出" },
  { keySource: "Ctrl\n+\nShift\n+\nM", desc: "视图: 切换 问题" },
  { keySource: "Ctrl\n+\n`", desc: "视图: 切换 终端" },
  { keySource: "Ctrl\n+\nB", desc: "视图: 切换侧边栏可见性" },
  { keySource: "Ctrl\n+\nK\nZ", desc: "视图: 切换禅模式" },
  { keySource: "Ctrl\n+\nJ", desc: "视图: 切换面板" },
  { keySource: "F11", desc: "视图: 切换全屏" },
  {
    keySource: "Ctrl\n+\nK\nShift\n+\nEnter",
    desc: "视图: 取消固定编辑器",
  },
  { keySource: "Ctrl\n+\nNumPad_Subtract", desc: "视图: 缩小" },
  { keySource: "Ctrl\n+\nShift\n+\n-", desc: "视图: 缩小" },
  { keySource: "Ctrl\n+\n-", desc: "视图: 缩小" },
  { keySource: "Ctrl\n+\nShift\n+\nX", desc: "视图: 显示 扩展" },
  { keySource: "Ctrl\n+\nShift\n+\nF", desc: "视图: 显示 搜索" },
  { keySource: "Ctrl\n+\nShift\n+\nG", desc: "视图: 显示 源代码管理" },
  { keySource: "Ctrl\n+\nShift\n+\nD", desc: "视图: 显示 运行和调试" },
  { keySource: "Ctrl\n+\nShift\n+\nE", desc: "视图: 显示 资源管理器" },
  { keySource: "Ctrl\n+\nK\nUpArrow", desc: "视图: 向上移动编辑器组" },
  { keySource: "Ctrl\n+\nK\nDownArrow", desc: "视图: 向下移动编辑器组" },
  {
    keySource: "Ctrl\n+\nShift\n+\nPageDown",
    desc: "视图: 向右移动编辑器",
  },
  { keySource: "Ctrl\n+\nK\nRightArrow", desc: "视图: 向右移动编辑器组" },
  { keySource: "Ctrl\n+\nShift\n+\nPageUp", desc: "视图: 向左移动编辑器" },
  { keySource: "Ctrl\n+\nK\nLeftArrow", desc: "视图: 向左移动编辑器组" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nShift\n+\n\\",
    desc: "视图: 在组中拆分编辑器",
  },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nShift\n+\n\\",
    desc: "视图: 在组中加入编辑器",
  },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n\\", desc: "视图: 正交拆分编辑器" },
  {
    keySource: "Ctrl\n+\nShift\n+\nT",
    desc: "视图: 重新打开已关闭的编辑器",
  },
  { keySource: "Ctrl\n+\nNumPad0", desc: "视图: 重置缩放" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nUpArrow",
    desc: "视图: 专注上述编辑器组",
  },
  { keySource: "Shift\n+\nF6", desc: "视图: 专注上一部分" },
  { keySource: "F6", desc: "视图: 专注下一部分" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nDownArrow",
    desc: "视图: 专注以下编辑器组",
  },
  { keySource: "Ctrl\n+\nQ", desc: "视图: Quick Open 视图" },
  { keySource: "Shift\n+\nAlt\n+\nLeftArrow", desc: "收起选择" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nS", desc: "首选项: 打开键盘快捷方式" },
  { keySource: "Escape", desc: "首选项: 将焦点上移一级" },
  { keySource: "LeftArrow", desc: "首选项: 聚焦到设置目录" },
  { keySource: "Ctrl\n+\nF", desc: "首选项: 聚焦到设置搜索" },
  { keySource: "Escape", desc: "首选项: 清除设置搜索结果" },
  { keySource: "Shift\n+\nF9", desc: "首选项: 显示设置上下文菜单" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nT", desc: "首选项: 颜色主题" },
  { keySource: "Shift\n+\nF4", desc: "搜索: 聚焦到上一搜索结果" },
  { keySource: "F4", desc: "搜索: 聚焦下一搜索结果" },
  { keySource: "Escape", desc: "搜索: 取消搜索" },
  { keySource: "Ctrl\n+\nShift\n+\nF", desc: "搜索: 在文件中查找" },
  { keySource: "Ctrl\n+\nShift\n+\nH", desc: "搜索: 在文件中替换" },
  { keySource: "Alt\n+\n-", desc: "搜索编辑器: 减少上下文行" },
  { keySource: "Escape", desc: "搜索编辑器: 聚焦搜索编辑器输入" },
  { keySource: "Alt\n+\nC", desc: "搜索编辑器: 切换匹配大小写" },
  { keySource: "Alt\n+\nW", desc: "搜索编辑器: 切换全字匹配" },
  { keySource: "Alt\n+\nL", desc: "搜索编辑器: 切换上下文行" },
  { keySource: "Alt\n+\nR", desc: "搜索编辑器: 切换使用正则表达式" },
  {
    keySource: "Ctrl\n+\nShift\n+\nBackspace",
    desc: "搜索编辑器: 删除文件结果",
  },
  { keySource: "Ctrl\n+\nShift\n+\nL", desc: "搜索编辑器: 选择所有匹配项" },
  { keySource: "Ctrl\n+\nShift\n+\nR", desc: "搜索编辑器: 再次搜索" },
  { keySource: "Alt\n+\nEnter", desc: "搜索编辑器: 在编辑器中打开结果" },
  { keySource: "Alt\n+\n=", desc: "搜索编辑器: 增加上下文行" },
  { keySource: "Alt\n+\nF12", desc: "速览定义" },
  { keySource: "Ctrl\n+\nH", desc: "替换" },
  { keySource: "Ctrl\n+\nShift\n+\n,", desc: "替换为上一个值" },
  { keySource: "Ctrl\n+\nShift\n+\n.", desc: "替换为下一个值" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nC", desc: "添加行注释" },
  { keySource: "Escape", desc: "通知: 隐藏通知" },
  { keySource: "Ctrl\n+\nS", desc: "文件: 保存" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nShift\n+\nS",
    desc: "文件: 保存但不更改格式",
  },
  { keySource: "Ctrl\n+\nK\nC", desc: "文件: 比较活动文件与剪贴板" },
  { keySource: "Ctrl\n+\nK\nD", desc: "文件: 比较活动与已保存的文件" },
  { keySource: "Ctrl\n+\nO", desc: "文件: 打开..." },
  { keySource: "Ctrl\n+\nO", desc: "文件: 打开文件..." },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nO", desc: "文件: 打开文件夹..." },
  { keySource: "Ctrl\n+\nR", desc: "文件: 打开最近的文件…" },
  { keySource: "Shift\n+\nAlt\n+\nC", desc: "文件: 复制活动文件的路径" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nShift\n+\nC",
    desc: "文件: 复制活动文件的相对路径",
  },
  { keySource: "Ctrl\n+\nShift\n+\nS", desc: "文件: 另存为..." },
  { keySource: "Ctrl\n+\nN", desc: "文件: 新的无标题文件" },
  {
    keySource: "Shift\n+\nAlt\n+\nR",
    desc: "文件: 在文件资源管理器中显示",
  },
  { keySource: "Ctrl\n+\nK\nO", desc: "文件: 在新窗口中打开活动文件" },
  { keySource: "Shift\n+\nF10", desc: "显示编辑器上下文菜单" },
  { keySource: "Alt\n+\nF1", desc: "显示辅助功能帮助" },
  { keySource: "Shift\n+\nAlt\n+\nF3", desc: "显示上一个更改" },
  { keySource: "Alt\n+\n[", desc: "显示上一个内联建议" },
  { keySource: "F1", desc: "显示所有命令" },
  { keySource: "Ctrl\n+\nShift\n+\nP", desc: "显示所有命令" },
  { keySource: "Alt\n+\nF3", desc: "显示下一个更改" },
  { keySource: "Alt\n+\n]", desc: "显示下一个内联建议" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nI", desc: "显示悬停" },
  { keySource: "Shift\n+\nAlt\n+\nUpArrow", desc: "向上复制行" },
  { keySource: "Alt\n+\nUpArrow", desc: "向上移动行" },
  { keySource: "Shift\n+\nAlt\n+\nDownArrow", desc: "向下复制行" },
  { keySource: "Alt\n+\nDownArrow", desc: "向下移动行" },
  { keySource: "Ctrl\n+\nShift\n+\nN", desc: "新建窗口" },
  { keySource: "Ctrl\n+\n[", desc: "行减少缩进" },
  { keySource: "Ctrl\n+\n]", desc: "行缩进" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nK", desc: "选择从定位点到光标" },
  { keySource: "Ctrl\n+\nA", desc: "选择全部" },
  { keySource: "Ctrl\n+\nShift\n+\nL", desc: "选择所有找到的查找匹配项" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n]", desc: "以递归方式展开" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n[", desc: "以递归方式折叠" },
  { keySource: "Ctrl\n+\nShift\n+\nEnter", desc: "在上面插入行" },
  { keySource: "Ctrl\n+\nAlt\n+\nUpArrow", desc: "在上面添加光标" },
  { keySource: "Ctrl\n+\nEnter", desc: "在下面插入行" },
  { keySource: "Ctrl\n+\nAlt\n+\nDownArrow", desc: "在下面添加光标" },
  { keySource: "Shift\n+\nAlt\n+\nI", desc: "在行尾添加光标" },
  { keySource: "Shift\n+\nInsert", desc: "粘贴" },
  { keySource: "Ctrl\n+\nV", desc: "粘贴" },
  { keySource: "Ctrl\n+\nShift\n+\n]", desc: "展开" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\n=",
    desc: "展开除所选区域之外的所有区域",
  },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n9", desc: "展开所有区域" },
  { keySource: "Ctrl\n+\nL", desc: "展开行选择" },
  { keySource: "Shift\n+\nAlt\n+\nRightArrow", desc: "展开选择" },
  { keySource: "Ctrl\n+\nShift\n+\n[", desc: "折叠" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\n-",
    desc: "折叠除所选区域之外的所有区域",
  },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n1", desc: "折叠级别 1" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n2", desc: "折叠级别 2" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n3", desc: "折叠级别 3" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n4", desc: "折叠级别 4" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n5", desc: "折叠级别 5" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n6", desc: "折叠级别 6" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n7", desc: "折叠级别 7" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n/", desc: "折叠所有块注释" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\n8", desc: "折叠所有区域" },
  { keySource: "Shift\n+\nAlt\n+\nO", desc: "整理 import 语句" },
  { keySource: "Shift\n+\nF3", desc: "终端: 查找上一个" },
  { keySource: "Enter", desc: "终端: 查找上一个" },
  { keySource: "F3", desc: "终端: 查找下一个" },
  { keySource: "Shift\n+\nEnter", desc: "终端: 查找下一个" },
  { keySource: "Ctrl\n+\nShift\n+\n5", desc: "终端: 拆分终端" },
  { keySource: "Ctrl\n+\nShift\n+\n`", desc: "终端: 创建新的终端" },
  { keySource: "Ctrl\n+\nShift\n+\nC", desc: "终端: 复制所选内容" },
  { keySource: "Ctrl\n+\nC", desc: "终端: 复制所选内容" },
  { keySource: "Ctrl\n+\nEnd", desc: "终端: 滚动到底部" },
  { keySource: "Ctrl\n+\nHome", desc: "终端: 滚动到顶部" },
  { keySource: "Alt\n+\nZ", desc: "终端: 将大小切换为内容宽度" },
  { keySource: "Ctrl\n+\nShift\n+\n\\", desc: "终端: 焦点终端选项卡视图" },
  { keySource: "Ctrl\n+\nF", desc: "终端: 聚焦查找" },
  { keySource: "Ctrl\n+\nUpArrow", desc: "终端: 聚焦上一行(导航模式)" },
  { keySource: "Ctrl\n+\nPageUp", desc: "终端: 聚焦上一终端组" },
  { keySource: "Ctrl\n+\nDownArrow", desc: "终端: 聚焦下一行(导航模式)" },
  { keySource: "Ctrl\n+\nPageDown", desc: "终端: 聚焦下一终端组" },
  { keySource: "Alt\n+\nC", desc: "终端: 切换使用区分大小写进行查找" },
  { keySource: "Alt\n+\nW", desc: "终端: 切换使用全字匹配进行查找" },
  { keySource: "Alt\n+\nR", desc: "终端: 切换使用正则表达式进行查找" },
  { keySource: "Escape", desc: "终端: 取消选择" },
  { keySource: "Ctrl\n+\nShift\n+\nF", desc: "终端: 搜索工作区" },
  { keySource: "Escape", desc: "终端: 退出导航模式" },
  { keySource: "Ctrl\n+\nAlt\n+\nPageUp", desc: "终端: 向上滚动(行)" },
  { keySource: "Shift\n+\nPageUp", desc: "终端: 向上滚动(页)" },
  { keySource: "Ctrl\n+\nAlt\n+\nPageDown", desc: "终端: 向下滚动(行)" },
  { keySource: "Shift\n+\nPageDown", desc: "终端: 向下滚动(页)" },
  { keySource: "Shift\n+\nEscape", desc: "终端: 隐藏查找" },
  { keySource: "Escape", desc: "终端: 隐藏查找" },
  { keySource: "Alt\n+\nUpArrow", desc: "终端: 在终端组中聚焦上一终端" },
  { keySource: "Alt\n+\nLeftArrow", desc: "终端: 在终端组中聚焦上一终端" },
  { keySource: "Alt\n+\nDownArrow", desc: "终端: 在终端组中聚焦下一终端" },
  { keySource: "Alt\n+\nRightArrow", desc: "终端: 在终端组中聚焦下一终端" },
  { keySource: "Ctrl\n+\nShift\n+\nV", desc: "终端: 粘贴到活动终端中" },
  { keySource: "Ctrl\n+\nV", desc: "终端: 粘贴到活动终端中" },
  { keySource: "Ctrl\n+\nW", desc: "终端: 终止编辑器区域中的活动终端" },
  { keySource: "Ctrl\n+\nF4", desc: "终端: 终止编辑器区域中的活动终端" },
  { keySource: "Ctrl\n+\nShift\n+\nR", desc: "重构..." },
  { keySource: "F2", desc: "重命名符号" },
  { keySource: "Ctrl\n+\nShift\n+\nO", desc: "转到编辑器中的符号..." },
  { keySource: "F12", desc: "转到定义" },
  { keySource: "Ctrl\n+\nT", desc: "转到工作区中的符号..." },
  { keySource: "Ctrl\n+\nShift\n+\n\\", desc: "转到括号" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nQ", desc: "转到上一编辑位置" },
  { keySource: "Shift\n+\nAlt\n+\nF5", desc: "转到上一个更改" },
  { keySource: "Shift\n+\nF7", desc: "转到上一个突出显示的符号" },
  {
    keySource: "Shift\n+\nAlt\n+\nF8",
    desc: "转到上一个问题 (错误、警告、信息)",
  },
  { keySource: "Ctrl\n+\nF12", desc: "转到实现" },
  { keySource: "Ctrl\n+\nE", desc: "转到文件..." },
  { keySource: "Ctrl\n+\nP", desc: "转到文件..." },
  {
    keySource: "Shift\n+\nF8",
    desc: "转到文件中的上一个问题 (错误、警告、信息)",
  },
  { keySource: "F8", desc: "转到文件中的下一个问题 (错误、警告、信息)" },
  { keySource: "Alt\n+\nF5", desc: "转到下一个更改" },
  { keySource: "F7", desc: "转到下一个突出显示的符号" },
  { keySource: "Alt\n+\nF8", desc: "转到下一个问题 (错误、警告、信息)" },
  { keySource: "Ctrl\n+\nG", desc: "转到行/列..." },
  { keySource: "Shift\n+\nF12", desc: "转到引用" },
  { keySource: "Shift\n+\nF7", desc: "转至上一个差异" },
  { keySource: "F7", desc: "转至下一个差异" },
  {
    keySource: "Ctrl\n+\nK\nE",
    desc: "资源管理器: 焦点在 打开的编辑器 视图上",
  },
  { keySource: "Shift\n+\nAlt\n+\n.", desc: "自动修复..." },
  { keySource: "Shift\n+\nAlt\n+\nH", desc: "Calls: Show Call Hierarchy" },
  { keySource: "F11", desc: "Debug: 单步调试" },
  { keySource: "Shift\n+\nF11", desc: "Debug: 单步跳出" },
  { keySource: "F10", desc: "Debug: 单步跳过" },
  { keySource: "Shift\n+\nF5", desc: "Debug: 断开连接" },
  { keySource: "F5", desc: "Debug: 继续" },
  { keySource: "F5", desc: "Debug: 开始调试" },
  { keySource: "Ctrl\n+\nF5", desc: "Debug: 开始执行(不调试)" },
  { keySource: "Shift\n+\nF9", desc: "Debug: 内联断点" },
  { keySource: "Shift\n+\nF5", desc: "Debug: 停止" },
  { keySource: "F6", desc: "Debug: 暂停" },
  { keySource: "Ctrl\n+\nShift\n+\nF5", desc: "Debug: 重启" },
  { keySource: "F10", desc: "Debug: Start Debugging and Stop on Entry" },
  { keySource: "F11", desc: "Debug: Start Debugging and Stop on Entry" },
  { keySource: "Tab", desc: "Emmet: 展开缩写" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nR", desc: "Git: 还原所选更改" },
  { keySource: "Ctrl\n+\nK\nCtrl\n+\nN", desc: "Git: 取消暂存所选范围" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nAlt\n+\nS",
    desc: "Git: 暂存所选范围",
  },
  { keySource: "F4", desc: "Go to Next Reference" },
  { keySource: "Shift\n+\nF4", desc: "Go to Previous Reference" },
  { keySource: "Ctrl\n+\nK\nV", desc: "Markdown: 打开侧边预览" },
  { keySource: "Ctrl\n+\nShift\n+\nV", desc: "Markdown: 打开预览" },
  {
    keySource: "Shift\n+\nAlt\n+\nF12",
    desc: "References: Find All References",
  },
  { keySource: "Ctrl\n+\nF", desc: "REPL 将内容聚焦到筛选器" },
  {
    keySource: "Shift\n+\nTab",
    desc: "acceptAlternativeSelectedSuggestion",
  },
  {
    keySource: "Shift\n+\nEnter",
    desc: "acceptAlternativeSelectedSuggestion",
  },
  { keySource: "Enter", desc: "acceptRenameInput" },
  { keySource: "Shift\n+\nEnter", desc: "acceptRenameInputWithPreview" },
  { keySource: "Tab", desc: "acceptSelectedSuggestion" },
  { keySource: "Enter", desc: "acceptSelectedSuggestion" },
  { keySource: "Ctrl\n+\nShift\n+\nL", desc: "addCursorsAtSearchResults" },
  { keySource: "Ctrl\n+\nShift\n+\n;", desc: "breadcrumbs.focus" },
  { keySource: "Ctrl\n+\nRightArrow", desc: "breadcrumbs.focusNext" },
  { keySource: "RightArrow", desc: "breadcrumbs.focusNext" },
  {
    keySource: "Ctrl\n+\nRightArrow",
    desc: "breadcrumbs.focusNextWithPicker",
  },
  { keySource: "Ctrl\n+\nLeftArrow", desc: "breadcrumbs.focusPrevious" },
  { keySource: "LeftArrow", desc: "breadcrumbs.focusPrevious" },
  {
    keySource: "Ctrl\n+\nLeftArrow",
    desc: "breadcrumbs.focusPreviousWithPicker",
  },
  { keySource: "Ctrl\n+\nEnter", desc: "breadcrumbs.revealFocused" },
  { keySource: "Space", desc: "breadcrumbs.revealFocused" },
  {
    keySource: "Ctrl\n+\nEnter",
    desc: "breadcrumbs.revealFocusedFromTreeAside",
  },
  { keySource: "Escape", desc: "breadcrumbs.selectEditor" },
  { keySource: "DownArrow", desc: "breadcrumbs.selectFocused" },
  { keySource: "Enter", desc: "breadcrumbs.selectFocused" },
  { keySource: "Ctrl\n+\nShift\n+\n.", desc: "breadcrumbs.toggleToOn" },
  { keySource: "Enter", desc: "breakpointWidget.action.acceptInput" },
  { keySource: "Shift\n+\nEscape", desc: "cancelLinkedEditingInput" },
  { keySource: "Escape", desc: "cancelLinkedEditingInput" },
  { keySource: "Shift\n+\nEscape", desc: "cancelRenameInput" },
  { keySource: "Escape", desc: "cancelRenameInput" },
  { keySource: "Shift\n+\nEscape", desc: "cancelSelection" },
  { keySource: "Escape", desc: "cancelSelection" },
  { keySource: "Shift\n+\nEscape", desc: "closeAccessibilityHelp" },
  { keySource: "Escape", desc: "closeAccessibilityHelp" },
  { keySource: "Shift\n+\nEscape", desc: "closeBreakpointWidget" },
  { keySource: "Escape", desc: "closeBreakpointWidget" },
  { keySource: "Shift\n+\nEscape", desc: "closeDirtyDiff" },
  { keySource: "Escape", desc: "closeDirtyDiff" },
  { keySource: "Shift\n+\nEscape", desc: "closeFindWidget" },
  { keySource: "Escape", desc: "closeFindWidget" },
  { keySource: "Shift\n+\nEscape", desc: "closeMarkersNavigation" },
  { keySource: "Escape", desc: "closeMarkersNavigation" },
  { keySource: "Shift\n+\nEscape", desc: "closeParameterHints" },
  { keySource: "Escape", desc: "closeParameterHints" },
  { keySource: "Shift\n+\nEscape", desc: "closeReferenceSearch" },
  { keySource: "Escape", desc: "closeReferenceSearch" },
  { keySource: "Shift\n+\nEscape", desc: "closeReferenceSearch" },
  { keySource: "Escape", desc: "closeReferenceSearch" },
  { keySource: "Escape", desc: "closeReplaceInFilesWidget" },
  { keySource: "Ctrl\n+\nEnd", desc: "cursorBottom" },
  { keySource: "Ctrl\n+\nShift\n+\nEnd", desc: "cursorBottomSelect" },
  {
    keySource: "Ctrl\n+\nShift\n+\nAlt\n+\nDownArrow",
    desc: "cursorColumnSelectDown",
  },
  { keySource: "Shift\n+\nDownArrow", desc: "cursorColumnSelectDown" },
  {
    keySource: "Ctrl\n+\nShift\n+\nAlt\n+\nLeftArrow",
    desc: "cursorColumnSelectLeft",
  },
  { keySource: "Shift\n+\nLeftArrow", desc: "cursorColumnSelectLeft" },
  {
    keySource: "Ctrl\n+\nShift\n+\nAlt\n+\nPageDown",
    desc: "cursorColumnSelectPageDown",
  },
  { keySource: "Shift\n+\nPageDown", desc: "cursorColumnSelectPageDown" },
  {
    keySource: "Ctrl\n+\nShift\n+\nAlt\n+\nPageUp",
    desc: "cursorColumnSelectPageUp",
  },
  { keySource: "Shift\n+\nPageUp", desc: "cursorColumnSelectPageUp" },
  {
    keySource: "Ctrl\n+\nShift\n+\nAlt\n+\nRightArrow",
    desc: "cursorColumnSelectRight",
  },
  { keySource: "Shift\n+\nRightArrow", desc: "cursorColumnSelectRight" },
  {
    keySource: "Ctrl\n+\nShift\n+\nAlt\n+\nUpArrow",
    desc: "cursorColumnSelectUp",
  },
  { keySource: "Shift\n+\nUpArrow", desc: "cursorColumnSelectUp" },
  { keySource: "DownArrow", desc: "cursorDown" },
  { keySource: "Ctrl\n+\nShift\n+\nDownArrow", desc: "cursorDownSelect" },
  { keySource: "Shift\n+\nDownArrow", desc: "cursorDownSelect" },
  { keySource: "End", desc: "cursorEnd" },
  { keySource: "Shift\n+\nEnd", desc: "cursorEndSelect" },
  { keySource: "Home", desc: "cursorHome" },
  { keySource: "Shift\n+\nHome", desc: "cursorHomeSelect" },
  { keySource: "LeftArrow", desc: "cursorLeft" },
  { keySource: "Shift\n+\nLeftArrow", desc: "cursorLeftSelect" },
  { keySource: "PageDown", desc: "cursorPageDown" },
  { keySource: "Shift\n+\nPageDown", desc: "cursorPageDownSelect" },
  { keySource: "PageUp", desc: "cursorPageUp" },
  { keySource: "Shift\n+\nPageUp", desc: "cursorPageUpSelect" },
  { keySource: "RightArrow", desc: "cursorRight" },
  { keySource: "Shift\n+\nRightArrow", desc: "cursorRightSelect" },
  { keySource: "Ctrl\n+\nHome", desc: "cursorTop" },
  { keySource: "Ctrl\n+\nShift\n+\nHome", desc: "cursorTopSelect" },
  { keySource: "UpArrow", desc: "cursorUp" },
  { keySource: "Ctrl\n+\nShift\n+\nUpArrow", desc: "cursorUpSelect" },
  { keySource: "Shift\n+\nUpArrow", desc: "cursorUpSelect" },
  { keySource: "Ctrl\n+\nRightArrow", desc: "cursorWordEndRight" },
  {
    keySource: "Ctrl\n+\nShift\n+\nRightArrow",
    desc: "cursorWordEndRightSelect",
  },
  { keySource: "Ctrl\n+\nLeftArrow", desc: "cursorWordLeft" },
  {
    keySource: "Ctrl\n+\nShift\n+\nLeftArrow",
    desc: "cursorWordLeftSelect",
  },
  { keySource: "Alt\n+\nEnter", desc: "debug.openBreakpointToSide" },
  { keySource: "Ctrl\n+\nEnter", desc: "debug.openBreakpointToSide" },
  { keySource: "Ctrl\n+\nF5", desc: "debug.openView" },
  { keySource: "F5", desc: "debug.openView" },
  { keySource: "Delete", desc: "debug.removeBreakpoint" },
  { keySource: "Delete", desc: "debug.removeWatchExpression" },
  { keySource: "F2", desc: "debug.renameWatchExpression" },
  { keySource: "F2", desc: "debug.setVariable" },
  { keySource: "Space", desc: "debug.toggleBreakpoint" },
  { keySource: "Shift\n+\nDelete", desc: "deleteFile" },
  { keySource: "Delete", desc: "deleteFile" },
  { keySource: "Shift\n+\nBackspace", desc: "deleteLeft" },
  { keySource: "Backspace", desc: "deleteLeft" },
  { keySource: "Delete", desc: "deleteRight" },
  { keySource: "Ctrl\n+\nBackspace", desc: "deleteWordLeft" },
  { keySource: "Ctrl\n+\nDelete", desc: "deleteWordRight" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nK",
    desc: "editor.action.defineKeybinding",
  },
  { keySource: "Enter", desc: "editor.action.extensioneditor.findNext" },
  {
    keySource: "Shift\n+\nEnter",
    desc: "editor.action.extensioneditor.findPrevious",
  },
  {
    keySource: "Ctrl\n+\nF",
    desc: "editor.action.extensioneditor.showfind",
  },
  { keySource: "Tab", desc: "editor.action.inlineSuggest.commit" },
  { keySource: "Escape", desc: "editor.action.inlineSuggest.hide" },
  { keySource: "Ctrl\n+\nAlt\n+\nEnter", desc: "editor.action.replaceAll" },
  { keySource: "Ctrl\n+\nShift\n+\n1", desc: "editor.action.replaceOne" },
  { keySource: "Enter", desc: "editor.action.replaceOne" },
  { keySource: "Alt\n+\nEnter", desc: "editor.action.selectAllMatches" },
  { keySource: "Enter", desc: "editor.action.webvieweditor.findNext" },
  {
    keySource: "Shift\n+\nEnter",
    desc: "editor.action.webvieweditor.findPrevious",
  },
  { keySource: "Escape", desc: "editor.action.webvieweditor.hideFind" },
  { keySource: "Ctrl\n+\nF", desc: "editor.action.webvieweditor.showFind" },
  { keySource: "Escape", desc: "editor.cancelOperation" },
  { keySource: "Escape", desc: "editor.closeCallHierarchy" },
  { keySource: "Escape", desc: "editor.closeTestPeek" },
  { keySource: "Escape", desc: "editor.closeTypeHierarchy" },
  { keySource: "F12", desc: "editor.gotoNextSymbolFromResult" },
  { keySource: "Escape", desc: "editor.gotoNextSymbolFromResult.cancel" },
  { keySource: "Shift\n+\nEnter", desc: "editor.refocusCallHierarchy" },
  { keySource: "Shift\n+\nEnter", desc: "editor.refocusTypeHierarchy" },
  { keySource: "Shift\n+\nAlt\n+\nH", desc: "editor.showCallHierarchy" },
  { keySource: "Shift\n+\nAlt\n+\nH", desc: "editor.showIncomingCalls" },
  { keySource: "Shift\n+\nAlt\n+\nH", desc: "editor.showOutgoingCalls" },
  { keySource: "Shift\n+\nAlt\n+\nH", desc: "editor.showSubtypes" },
  { keySource: "Shift\n+\nAlt\n+\nH", desc: "editor.showSupertypes" },
  { keySource: "Enter", desc: "explorer.openAndPassFocus" },
  { keySource: "Ctrl\n+\nEnter", desc: "explorer.openToSide" },
  { keySource: "Escape", desc: "filesExplorer.cancelCut" },
  { keySource: "Ctrl\n+\nC", desc: "filesExplorer.copy" },
  { keySource: "Ctrl\n+\nX", desc: "filesExplorer.cut" },
  { keySource: "Shift\n+\nAlt\n+\nF", desc: "filesExplorer.findInFolder" },
  { keySource: "Space", desc: "filesExplorer.openFilePreserveFocus" },
  { keySource: "Ctrl\n+\nV", desc: "filesExplorer.paste" },
  { keySource: "Home", desc: "firstCompressedFolder" },
  { keySource: "F12", desc: "goToNextReference" },
  { keySource: "F4", desc: "goToNextReference" },
  { keySource: "Shift\n+\nF12", desc: "goToPreviousReference" },
  { keySource: "Shift\n+\nF4", desc: "goToPreviousReference" },
  { keySource: "Shift\n+\nEscape", desc: "hideSuggestWidget" },
  { keySource: "Escape", desc: "hideSuggestWidget" },
  { keySource: "Alt\n+\nDownArrow", desc: "history.showNext" },
  { keySource: "DownArrow", desc: "history.showNext" },
  { keySource: "Alt\n+\nUpArrow", desc: "history.showPrevious" },
  { keySource: "UpArrow", desc: "history.showPrevious" },
  { keySource: "Tab", desc: "insertBestCompletion" },
  { keySource: "Tab", desc: "insertNextSuggestion" },
  { keySource: "Shift\n+\nTab", desc: "insertPrevSuggestion" },
  { keySource: "Tab", desc: "insertSnippet" },
  { keySource: "Ctrl\n+\nEnter", desc: "interactive.execute" },
  { keySource: "DownArrow", desc: "interactive.history.next" },
  { keySource: "UpArrow", desc: "interactive.history.previous" },
  { keySource: "Ctrl\n+\nEnd", desc: "interactive.scrollToBottom" },
  { keySource: "Ctrl\n+\nHome", desc: "interactive.scrollToTop" },
  { keySource: "Tab", desc: "jumpToNextSnippetPlaceholder" },
  { keySource: "Shift\n+\nTab", desc: "jumpToPrevSnippetPlaceholder" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nA",
    desc: "keybindings.editor.addKeybinding",
  },
  { keySource: "Escape", desc: "keybindings.editor.clearSearchResults" },
  {
    keySource: "Ctrl\n+\nC",
    desc: "keybindings.editor.copyKeybindingEntry",
  },
  { keySource: "Enter", desc: "keybindings.editor.defineKeybinding" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nE",
    desc: "keybindings.editor.defineWhenExpression",
  },
  {
    keySource: "Ctrl\n+\nDownArrow",
    desc: "keybindings.editor.focusKeybindings",
  },
  { keySource: "Alt\n+\nK", desc: "keybindings.editor.recordSearchKeys" },
  { keySource: "Delete", desc: "keybindings.editor.removeKeybinding" },
  { keySource: "Ctrl\n+\nF", desc: "keybindings.editor.searchKeybindings" },
  {
    keySource: "Alt\n+\nP",
    desc: "keybindings.editor.toggleSortByPrecedence",
  },
  { keySource: "End", desc: "lastCompressedFolder" },
  { keySource: "Escape", desc: "leaveEditorMessage" },
  { keySource: "Shift\n+\nEscape", desc: "leaveSnippet" },
  { keySource: "Escape", desc: "leaveSnippet" },
  { keySource: "Escape", desc: "list.clear" },
  { keySource: "LeftArrow", desc: "list.collapse" },
  { keySource: "Ctrl\n+\nLeftArrow", desc: "list.collapseAll" },
  { keySource: "RightArrow", desc: "list.expand" },
  { keySource: "Shift\n+\nDownArrow", desc: "list.expandSelectionDown" },
  { keySource: "Shift\n+\nUpArrow", desc: "list.expandSelectionUp" },
  { keySource: "DownArrow", desc: "list.focusDown" },
  { keySource: "Home", desc: "list.focusFirst" },
  { keySource: "End", desc: "list.focusLast" },
  { keySource: "PageDown", desc: "list.focusPageDown" },
  { keySource: "PageUp", desc: "list.focusPageUp" },
  { keySource: "UpArrow", desc: "list.focusUp" },
  { keySource: "Ctrl\n+\nDownArrow", desc: "list.scrollDown" },
  { keySource: "Ctrl\n+\nUpArrow", desc: "list.scrollUp" },
  { keySource: "Enter", desc: "list.select" },
  { keySource: "Ctrl\n+\nA", desc: "list.selectAll" },
  { keySource: "Space", desc: "list.toggleExpand" },
  { keySource: "Ctrl\n+\nShift\n+\nEnter", desc: "list.toggleSelection" },
  { keySource: "Delete", desc: "moveFileToTrash" },
  { keySource: "RightArrow", desc: "nextCompressedFolder" },
  { keySource: "Ctrl\n+\nF", desc: "notebook.find" },
  { keySource: "Escape", desc: "notebook.hideFind" },
  { keySource: "Delete", desc: "notification.clear" },
  { keySource: "LeftArrow", desc: "notification.collapse" },
  { keySource: "RightArrow", desc: "notification.expand" },
  { keySource: "Enter", desc: "notification.toggle" },
  { keySource: "Space", desc: "notification.toggle" },
  { keySource: "Home", desc: "notifications.focusFirstToast" },
  { keySource: "PageUp", desc: "notifications.focusFirstToast" },
  { keySource: "End", desc: "notifications.focusLastToast" },
  { keySource: "PageDown", desc: "notifications.focusLastToast" },
  { keySource: "DownArrow", desc: "notifications.focusNextToast" },
  { keySource: "UpArrow", desc: "notifications.focusPreviousToast" },
  { keySource: "Escape", desc: "notifications.hideToasts" },
  { keySource: "Escape", desc: "notifications.hideToasts" },
  { keySource: "Ctrl\n+\nEnter", desc: "openReferenceToSide" },
  { keySource: "Shift\n+\nTab", desc: "outdent" },
  { keySource: "LeftArrow", desc: "previousCompressedFolder" },
  { keySource: "Ctrl\n+\nC", desc: "problems.action.copy" },
  { keySource: "Ctrl\n+\nF", desc: "problems.action.focusFilter" },
  {
    keySource: "Ctrl\n+\nDownArrow",
    desc: "problems.action.focusProblemsFromFilter",
  },
  { keySource: "Enter", desc: "problems.action.open" },
  { keySource: "Ctrl\n+\nEnter", desc: "problems.action.openToSide" },
  { keySource: "Ctrl\n+\n.", desc: "problems.action.showQuickFixes" },
  { keySource: "Shift\n+\nEnter", desc: "refactorPreview.apply" },
  { keySource: "Space", desc: "refactorPreview.toggleCheckedState" },
  { keySource: "Delete", desc: "remote.tunnel.closeInline" },
  { keySource: "Ctrl\n+\nC", desc: "remote.tunnel.copyAddressInline" },
  { keySource: "F2", desc: "remote.tunnel.label" },
  { keySource: "Shift\n+\nEscape", desc: "removeSecondaryCursors" },
  { keySource: "Escape", desc: "removeSecondaryCursors" },
  { keySource: "F2", desc: "renameFile" },
  { keySource: "Enter", desc: "revealReference" },
  { keySource: "Ctrl\n+\nK\nS", desc: "saveAll" },
  { keySource: "Ctrl\n+\nEnter", desc: "scm.acceptInput" },
  { keySource: "Alt\n+\nDownArrow", desc: "scm.forceViewNextCommit" },
  { keySource: "Alt\n+\nUpArrow", desc: "scm.forceViewPreviousCommit" },
  { keySource: "DownArrow", desc: "scm.viewNextCommit" },
  { keySource: "UpArrow", desc: "scm.viewPreviousCommit" },
  { keySource: "Ctrl\n+\nDownArrow", desc: "scrollLineDown" },
  { keySource: "Ctrl\n+\nUpArrow", desc: "scrollLineUp" },
  { keySource: "Alt\n+\nPageDown", desc: "scrollPageDown" },
  { keySource: "Alt\n+\nPageUp", desc: "scrollPageUp" },
  { keySource: "Ctrl\n+\nC", desc: "search.action.copyMatch" },
  { keySource: "Shift\n+\nAlt\n+\nC", desc: "search.action.copyPath" },
  {
    keySource: "Ctrl\n+\nUpArrow",
    desc: "search.action.focusSearchFromResults",
  },
  { keySource: "Enter", desc: "search.action.openResult" },
  { keySource: "Ctrl\n+\nEnter", desc: "search.action.openResultToSide" },
  { keySource: "Delete", desc: "search.action.remove" },
  { keySource: "Ctrl\n+\nShift\n+\n1", desc: "search.action.replace" },
  { keySource: "Ctrl\n+\nAlt\n+\nEnter", desc: "search.action.replaceAll" },
  {
    keySource: "Ctrl\n+\nShift\n+\nEnter",
    desc: "search.action.replaceAllInFile",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\n1",
    desc: "search.action.replaceAllInFile",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nEnter",
    desc: "search.action.replaceAllInFolder",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\n1",
    desc: "search.action.replaceAllInFolder",
  },
  { keySource: "Ctrl\n+\nDownArrow", desc: "search.focus.nextInputBox" },
  { keySource: "Ctrl\n+\nUpArrow", desc: "search.focus.previousInputBox" },
  { keySource: "Ctrl\n+\nPageDown", desc: "selectNextPageSuggestion" },
  { keySource: "PageDown", desc: "selectNextPageSuggestion" },
  { keySource: "Ctrl\n+\nDownArrow", desc: "selectNextSuggestion" },
  { keySource: "DownArrow", desc: "selectNextSuggestion" },
  { keySource: "Ctrl\n+\nPageUp", desc: "selectPrevPageSuggestion" },
  { keySource: "PageUp", desc: "selectPrevPageSuggestion" },
  { keySource: "Ctrl\n+\nUpArrow", desc: "selectPrevSuggestion" },
  { keySource: "UpArrow", desc: "selectPrevSuggestion" },
  { keySource: "Enter", desc: "settings.action.focusSettingControl" },
  { keySource: "DownArrow", desc: "settings.action.focusSettingsFile" },
  {
    keySource: "DownArrow",
    desc: "settings.action.focusSettingsFromSearch",
  },
  { keySource: "Enter", desc: "settings.action.focusSettingsList" },
  { keySource: "Alt\n+\nDownArrow", desc: "showNextParameterHint" },
  { keySource: "DownArrow", desc: "showNextParameterHint" },
  { keySource: "Alt\n+\nUpArrow", desc: "showPrevParameterHint" },
  { keySource: "UpArrow", desc: "showPrevParameterHint" },
  { keySource: "Tab", desc: "tab" },
  { keySource: "Ctrl\n+\n;\nCtrl\n+\nX", desc: "testing.cancelRun" },
  { keySource: "Alt\n+\nEnter", desc: "testing.editFocusedTest" },
  { keySource: "Ctrl\n+\n/", desc: "toggleExplainMode" },
  { keySource: "Alt\n+\nC", desc: "toggleFindCaseSensitive" },
  { keySource: "Alt\n+\nL", desc: "toggleFindInSelection" },
  { keySource: "Alt\n+\nR", desc: "toggleFindRegex" },
  { keySource: "Alt\n+\nW", desc: "toggleFindWholeWord" },
  { keySource: "Ctrl\n+\nK\nF2", desc: "togglePeekWidgetFocus" },
  { keySource: "Alt\n+\nP", desc: "togglePreserveCase" },
  { keySource: "Alt\n+\nC", desc: "toggleSearchCaseSensitive" },
  { keySource: "Alt\n+\nP", desc: "toggleSearchPreserveCase" },
  { keySource: "Alt\n+\nR", desc: "toggleSearchRegex" },
  { keySource: "Alt\n+\nW", desc: "toggleSearchWholeWord" },
  { keySource: "Ctrl\n+\nI", desc: "toggleSuggestionDetails" },
  { keySource: "Ctrl\n+\nSpace", desc: "toggleSuggestionDetails" },
  { keySource: "Ctrl\n+\nAlt\n+\nSpace", desc: "toggleSuggestionFocus" },
  { keySource: "Ctrl\n+\nK\nDownArrow", desc: "views.moveViewDown" },
  { keySource: "Ctrl\n+\nK\nLeftArrow", desc: "views.moveViewLeft" },
  { keySource: "Ctrl\n+\nK\nRightArrow", desc: "views.moveViewRight" },
  { keySource: "Ctrl\n+\nK\nUpArrow", desc: "views.moveViewUp" },
  { keySource: "Ctrl\n+\nW", desc: "workbench.action.closeGroup" },
  { keySource: "Ctrl\n+\nF4", desc: "workbench.action.closeGroup" },
  {
    keySource: "Shift\n+\nEscape",
    desc: "workbench.action.closeQuickOpen",
  },
  { keySource: "Escape", desc: "workbench.action.closeQuickOpen" },
  {
    keySource: "Alt\n+\nF5",
    desc: "workbench.action.compareEditor.nextChange",
  },
  {
    keySource: "Shift\n+\nAlt\n+\nF5",
    desc: "workbench.action.compareEditor.previousChange",
  },
  { keySource: "Escape\nEscape", desc: "workbench.action.exitZenMode" },
  {
    keySource: "Ctrl\n+\nK\nP",
    desc: "workbench.action.files.copyPathOfActiveFile",
  },
  { keySource: "Ctrl\n+\nO", desc: "workbench.action.files.openLocalFile" },
  {
    keySource: "Ctrl\n+\nK\nCtrl\n+\nO",
    desc: "workbench.action.files.openLocalFolder",
  },
  {
    keySource: "Ctrl\n+\nK\nR",
    desc: "workbench.action.files.revealActiveFileInWindows",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nS",
    desc: "workbench.action.files.saveLocalFile",
  },
  {
    keySource: "Ctrl\n+\n8",
    desc: "workbench.action.focusEighthEditorGroup",
  },
  {
    keySource: "Ctrl\n+\n5",
    desc: "workbench.action.focusFifthEditorGroup",
  },
  {
    keySource: "Ctrl\n+\n4",
    desc: "workbench.action.focusFourthEditorGroup",
  },
  {
    keySource: "Ctrl\n+\n2",
    desc: "workbench.action.focusSecondEditorGroup",
  },
  {
    keySource: "Ctrl\n+\n7",
    desc: "workbench.action.focusSeventhEditorGroup",
  },
  {
    keySource: "Ctrl\n+\n6",
    desc: "workbench.action.focusSixthEditorGroup",
  },
  {
    keySource: "Ctrl\n+\n3",
    desc: "workbench.action.focusThirdEditorGroup",
  },
  { keySource: "Shift\n+\nEscape", desc: "workbench.action.hideComment" },
  { keySource: "Escape", desc: "workbench.action.hideComment" },
  {
    keySource: "DownArrow",
    desc: "workbench.action.interactivePlayground.arrowDown",
  },
  {
    keySource: "UpArrow",
    desc: "workbench.action.interactivePlayground.arrowUp",
  },
  {
    keySource: "PageDown",
    desc: "workbench.action.interactivePlayground.pageDown",
  },
  {
    keySource: "PageUp",
    desc: "workbench.action.interactivePlayground.pageUp",
  },
  { keySource: "Alt\n+\n1", desc: "workbench.action.openEditorAtIndex1" },
  { keySource: "Alt\n+\n2", desc: "workbench.action.openEditorAtIndex2" },
  { keySource: "Alt\n+\n3", desc: "workbench.action.openEditorAtIndex3" },
  { keySource: "Alt\n+\n4", desc: "workbench.action.openEditorAtIndex4" },
  { keySource: "Alt\n+\n5", desc: "workbench.action.openEditorAtIndex5" },
  { keySource: "Alt\n+\n6", desc: "workbench.action.openEditorAtIndex6" },
  { keySource: "Alt\n+\n7", desc: "workbench.action.openEditorAtIndex7" },
  { keySource: "Alt\n+\n8", desc: "workbench.action.openEditorAtIndex8" },
  { keySource: "Alt\n+\n9", desc: "workbench.action.openEditorAtIndex9" },
  { keySource: "Ctrl\n+\n,", desc: "workbench.action.openSettings" },
  {
    keySource: "Alt\n+\nLeftArrow",
    desc: "workbench.action.quickInputBack",
  },
  {
    keySource: "Ctrl\n+\nTab",
    desc: "workbench.action.quickOpenNavigateNextInEditorPicker",
  },
  {
    keySource: "Ctrl\n+\nE",
    desc: "workbench.action.quickOpenNavigateNextInFilePicker",
  },
  {
    keySource: "Ctrl\n+\nP",
    desc: "workbench.action.quickOpenNavigateNextInFilePicker",
  },
  {
    keySource: "Ctrl\n+\nR",
    desc: "workbench.action.quickOpenNavigateNextInRecentFilesPicker",
  },
  {
    keySource: "Ctrl\n+\nQ",
    desc: "workbench.action.quickOpenNavigateNextInViewPicker",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nTab",
    desc: "workbench.action.quickOpenNavigatePreviousInEditorPicker",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nE",
    desc: "workbench.action.quickOpenNavigatePreviousInFilePicker",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nP",
    desc: "workbench.action.quickOpenNavigatePreviousInFilePicker",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nR",
    desc: "workbench.action.quickOpenNavigatePreviousInRecentFilesPicker",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nQ",
    desc: "workbench.action.quickOpenNavigatePreviousInViewPicker",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\nJ",
    desc: "workbench.action.search.toggleQueryDetails",
  },
  { keySource: "Ctrl\n+\nEnter", desc: "workbench.action.submitComment" },
  { keySource: "Delete", desc: "workbench.action.terminal.killInstance" },
  { keySource: "F2", desc: "workbench.action.terminal.renameInstance" },
  {
    keySource: "Ctrl\n+\nV",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\nBackspace",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\nBackspace",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\nDelete",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\n2",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\n6",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\n/",
    desc: "workbench.action.terminal.sendSequence",
  },
  {
    keySource: "Ctrl\n+\nShift\n+\n5",
    desc: "workbench.action.terminal.splitInstance",
  },
  { keySource: "Escape", desc: "workbench.banner.focusBanner" },
  { keySource: "DownArrow", desc: "workbench.banner.focusNextAction" },
  { keySource: "RightArrow", desc: "workbench.banner.focusNextAction" },
  { keySource: "UpArrow", desc: "workbench.banner.focusPreviousAction" },
  { keySource: "LeftArrow", desc: "workbench.banner.focusPreviousAction" },
  { keySource: "Escape", desc: "workbench.statusBar.clearFocus" },
  { keySource: "Home", desc: "workbench.statusBar.focusFirst" },
  { keySource: "End", desc: "workbench.statusBar.focusLast" },
  { keySource: "DownArrow", desc: "workbench.statusBar.focusNext" },
  { keySource: "RightArrow", desc: "workbench.statusBar.focusNext" },
  { keySource: "UpArrow", desc: "workbench.statusBar.focusPrevious" },
  { keySource: "LeftArrow", desc: "workbench.statusBar.focusPrevious" },
]
const json = {}

table.forEach(item=>{
  var group = '编辑'
  if(/^[\w.]+$/g.test(item.desc)){
    group = '未描述'
  }else if(/:/.test(item.desc)){
    var descArr = item.desc.split(/:/g)
    group = descArr.shift()
    item.desc = descArr.join(':')
  }
  if(!json[group]) json[group] = []
  item.key = [[]]
  item.keySource
    .replace(/LeftArrow/g, '←')
    .replace(/RightArrow/g, '→')
    .replace(/UpArrow/g, '↑')
    .replace(/DownArrow/g, '↓')
    .replace(/Windows/g, 'Win')
    .split(/\n\+\n/g).forEach(keys=>{
      if(/\n/g.test(keys)){
        keys.split(/\n/g).forEach((key, i)=>{
          if(i){ item.key[0].push('then') }
          item.key[0].push(key)
        })
        return
      }
      item.key[0].push(keys)
  })
  json[group].push(item)
})

const result = new Array(Object.keys(json).length)
const titleArr = [
  '开始',
  '创建',
  '文件',
  '资源管理器',
  '编辑',
  '搜索',
  '搜索编辑器',
  '查看',
  '视图',
  '工作区',

  '开发人员',
  'Debug',
  '调试',
  '测试',
  '终端',

  '笔记本',
  '任务',
  '首选项',
  '帮助',
  '通知',
  'Calls',
  'Emmet',
  'Git',
  'Markdown',
  'References',
  '未描述'
]
for(const title in json){
  const index = titleArr.indexOf(title)
  if(index!==-1){
    result[index] = {
      title,
      table: json[title]
    }
    continue
  }
  console.log(title)
}

console.log(JSON.stringify(result, '', 2))